stages:
  - test
  - build
  - deploy

test:
  image: node:9.3
  stage: test
  script: 
    - make prepare
    - make test
  only:
    - branches

build:
  image: node:9.3
  stage: build
  script: 
    - make prepare
    - make build
  artifacts:
    paths:
      - .build/
    expire_in: 1 week
  only:
    - schedules
    - master
    - release   
